export enum UserErrorCode {
  LOGIN_ID_DUPLICATED = 'USER_LOGIN_ID_DUPLICATED',
  REGISTER_FAILED = 'USER_REGISTER_FAILED',
  GUEST_DELETE_FAILED = 'USER_GUEST_DELETE_FAILED',
}

export enum CommonErrorCode {
  VALIDATION_ERROR = 'COMMON_VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'COMMON_INTERNAL_SERVER_ERROR',
}
