server {
    listen 80;
    server_name _;

    # React 정적 파일 서빙
    location / {
        root /usr/share/nginx/html;          # React 빌드 파일 경로
        index index.html index.htm;          # 기본 파일
        try_files $uri $uri/ /index.html;    # SPA 라우팅 처리
    }

    # API 요청을 백엔드로 프록시
    location /api {

        # 백엔드 컨테이너 이름
        # docker-compose 에선 'localhost'로 접근 불가
        proxy_pass http://nest:8080;

        rewrite ^/api(/.*)$ $1 break;  # /api/ 제거
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
    }
}
