export enum ReservationErrorCode {
  NOT_FOUND = 'RESERVATION_NOT_FOUND',
  INVALID_SEAT_COUNT = 'RESERVATION_INVALID_SEAT_COUNT',
  SESSION_EVENT_NOT_FOUND = 'RESERVATION_SESSION_EVENT_NOT_FOUND',
  UNBOOKED_SEAT_INCLUDED = 'RESERVATION_UNBOOKED_SEAT_INCLUDED',
  INVALID_INFO = 'RESERVATION_INVALID_INFO',
  CREATE_FAILED = 'RESERVATION_CREATE_FAILED',
  SECTION_NOT_FOUND = 'RESERVATION_SECTION_NOT_FOUND',
  SEAT_OUT_OF_RANGE = 'RESERVATION_SEAT_OUT_OF_RANGE',
}
