export enum AuthErrorCode {
  UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  FORBIDDEN = 'AUTH_FORBIDDEN',
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  USER_INFO_FETCH_FAILED = 'AUTH_USER_INFO_FETCH_FAILED',
  LOGOUT_FAILED = 'AUTH_LOGOUT_FAILED',
  GUEST_CREATE_FAILED = 'AUTH_GUEST_CREATE_FAILED',
}
